---
- name: Playbook to update Windows Update settings
  hosts: win10
  gather_facts: no
  tasks:
    - name: Remove Windows Update policies registry key
      win_regedit:
        path: HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate
        state: absent
      register: remove_registry

    - name: Force group policy update
      win_shell: gpupdate /force
      when: remove_registry.changed
      register: gpupdate_force
      failed_when: "'Error' in gpupdate_force.stderr or gpupdate_force.rc != 0"

    - name: Restart Windows Update service
      win_service:
        name: wuauserv
        state: restarted
      when: gpupdate_force.changed
